export const apiUrl =  'http://192.168.0.195:5000/api';
export const LOCAL_STORAGE_TOKEN_NAME = 'user-admin';

export const SET_AUTH = 'SET_AUTH';

export const LOCAL_STORAGE_TOKEN_NAME_CLIENT = 'user';

export const SET_AUTH_CLIENT = 'SET_AUTH_CLIENT';

export const PRODUCT_LOADED_SUCCESS = 'PRODUCT_LOADED_SUCCESS';
export const PRODUCT_LOADED_FAIL = 'PRODUCT_LOADED_FAIL';
export const CATEGORY_PRODUCT_FIND_BY_ID_LOADED_SUCCESS = 'CATEGORY_PRODUCT_FIND_BY_ID_LOADED_SUCCESS';
export const CATEGORY_PRODUCT_FIND_BY_ID_LOADED_FAIL = 'CATEGORY_PRODUCT_FIND_BY_ID_LOADED_FAIL';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_FIND = 'PRODUCT_FIND';
export const PRODUCTS_FIND = 'PRODUCTS_FIND';
export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS';
export const PRODUCTS_LOADED_FAIL = 'PRODUCTS_LOADED_FAIL';